[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  RESEND_API_KEY = "re_2PKRsxvp_NhNkwPxdRHyTGGb7LnqTNhSs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
